apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuard
spec:
  destination:
    namespace: ${namespace}
    server: 'https://kubernetes.default.svc'
  source:
    path: ${path}
    repoURL: ${url}
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
