# kustomize https://kustomize.io/
#
# This uses kustomize which provides a template
# free way of customising application configuration

kustomize_apply_opts  ?=
kustomize_delete_opts ?=

.kustomization := kustomization.yml

$(.kustomization):
	$(error cannot create or delete the kustomize manifest if no kustomization is provided)

# Applies the provided manifest as generated by kustomized
# to the kubernetes cluster
.PHONY: create-kustomization
create-kustomization: $(.kustomization)
	$(KUBECTL) apply $(kustomize_apply_opts) \
		-k .

# Deletes the provided manifest from the kubernetes
# cluster
.PHONY: delete-kustomization
delete-kustomization: $(.kustomization)
	$(KUBECTL) delete $(kustomize_delete_opts) \
		--ignore-not-found=true \
		-k .
